#Working with json objects generated by Survey Monkey API

from survey_monkey_api import *


def main():
    # access survey monkey api
    local_file = '/Users/nbrodnax/Indiana/CEWIT/survey_monkey_auth.txt'
    survey_id = '48173850'


def get_structure(json_object, nest=0):
    """Displays the names and types of nested objects.

    json object -> none"""
    if not isinstance(json_object, list):
        if not isinstance(json_object, dict):
            print('    '*nest + str(json_object) + ' has type ' +
                  str(type(json_object)))
        else:
            nest += 1
            for item in json_object.items():
                print('    '*nest + str(item[0]) + ' has type ' +
                      str(type(item[1])))
                get_structure(item[1], nest)
    else:
        nest += 1
        for child in json_object:
            get_structure(child, nest)
    # this is giving me an extra layer for values rather than just keys


def get_questions(survey_id, auth_filename):
    """Returns a dictionary of question ids and answer ids.

    str, str -> dict of str"""
    auth = credentials(auth_filename)
    api = ApiService(auth['key'], auth['token'])

    # get survey details
    data = {"survey_id": survey_id}
    details = api.get_survey_details(data)

    # get list of questions and answers
    pages = details["data"]["pages"]
    contents = [x.get("questions") for x in pages if isinstance(x, dict)]
    questions = {}
    for page in contents:
        for question in page:
            question_id = question.get("question_id")
            question_text = question.get("heading")
            answers = question.get("answers")
            if len(answers) == 0:
                answer_id = '0'
            else:
                answer_id = [(a.get("answer_id"): a.get("text"))
                             for a in answers]
            questions[question_id] = [question_text, answer_id]
    return questions


def get_respondent_ids(survey_id, auth_filename):
    """Returns a list of respondent ids

    str, str -> list"""
    auth = credentials(auth_filename)
    api = ApiService(auth['key'], auth['token'])
    data = {"survey_id": survey_id}
    respondents = api.get_respondent_list(data)
    return [r.get("respondent_id") for r in respondents["data"]]


def get_responses(json_object, question_id):
    """Returns a list of responses by respondent id for a given question id

    json_object, str -> list of dict"""
    
if __name__ == '__main__':
    main()